[package]
name = "tss-rust"
version = "0.1.0"
edition = "2021"

[lints.rust]
non_camel_case_types = "allow"
unused-parens = "allow"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
lazy_static = "1.5.0"

[[example]]
name = "tpm_samples"
path = "examples/tpm_samples.rs"
